#+TITLE: Kayıp Kıta Serüvenleri
* İlave Kurallar
** Karakter Takdimi
FRP, söze dayalı bir oyun olduğu için, karakterlerin fiziksel
özellikleri kolayca akıldan çıkabilir. Buna engel olmak için
karakterini belli periyotlarda yeniden takdim etmeni
isteyebilirim. Bunu ezberden yapmak her zaman kolay olmadığından,
fiziksel özelliklerini kısaca not alman gerekebilir.

Bunun için karakterinin dışarıdan bakınca algılanan özelliklerine
odaklan, ve aşağıdaki beş maddeye, bir iki cümleyle kısaca değin.

1. *Genel Fizik.* Irk, cinsiyet, etnisite, vücut yapın, ve göründüğü
   kadarıyla yaşın.
2. *Silah, Zırh ve Kıyafetler.* Görünen silahların, ve onları taşıdığın
   yerler. Giydiğin zırh veya kıyafetlerin genel özellikleri.
3. *Semboller ve Süsler.* Üzerinde bulunan kutsal semboller, takılar,
   kalkanındaki armalar, vs. Ve bunların oyun dünyasındaki anlamları.
4. *Özgün Nitelik.* Karakterini diğerlerinden ayıran önemli bir
   detay. Bu fiziksel bir özelliğin, taşıdığın bir şey, kendine has
   duruşun, tutumun vb. bir niteliği kapsayabilir.
5. *Yeni Detay.* Karakterinin yakın zamanda, oyun esnasında ortaya çıkan
   bir detayı. Bu herhangi bir şey olabilir: Kullandığın bir hünerin,
   geçmişine dair ortaya çıkan yeni bir bilgi, veya birayı şaraba
   tercih etmen, gibi.

Anlatımın sırasında, niteliğe dayalı tariflerden çok, hayal gücünde
çağrışımlar yapabilen anlam yüklü kelimeler tercih et. Örneğin
kılığını anlatırken, "çizgili, saten bir pantolon; yeşil, dökümlü bir
bluz; ve bağcıklı mor bir korse" yerine, "gezgin bir göstericinin
cafcaflı kostümü" ifadesini kullanmak, tarifini daha etkili ve kolay
kavranır hale getirir.

Örnek bir karakter takdimi aşağıdadır:

1. *Genel Fizik.* Karpin, narin yapılı, genç bir erkek. Tipik bir
   Radovyalı gibi esmer, köşeli yüz hatlarına sahip ve bıyıklı.
2. *Silah, Zırh ve Kıyafetler.* Sırtında beceriksizce taşıdığı
   arbaletine ilaveten yanından sarkan bir sopası var. Sonbahar
   renklerinde soylu kıyafetleri ve uzun bir pelerin giyiyor.
3. *Semboller ve Süsler.* Yüzüğünde çok da ihtişamlı görünmeyen bir
   soylu mührü taşıyor.
4. *Özgün Nitelik.* Sıkça avcunda gezdirdiği bir altın sikkeye sahip.
5. *Yeni Detay.* Kirli çıkı bir yönü var. Son macerada çantasından soylu
   babasından habersizce aldığı şifa iksirleri çıktı.
** Seans Katılımı ve XP
Eğer bir sebepten ötürü oyun seansına katılamazsan, karakterinin
idaresini bana devretmiş sayılırsın. Bu durumda, öncelikle o seans
için, karakterini gruptan ayırmaya çalışırım. Elbette bunun için
grubun elverişli bir yerde olması gerekir. Örneğin bir yerleşim
yerindeyseniz, karakterinin kendi başına bir şeyler yapıyor olması
akla yatkındır.

Ancak bu hep mümkün olmaz. Zindanın ortasındayken, karakterinin bir
seanslığına ortadan kaybolup gelmesi, hikaye devamlılığına zarar
verir. Dolayısıyla bu gibi durumlarda, karakterini tıpkı bir NPC gibi
ben kontrol ederim. Mekanik özelliklerinin idaresini ise bir başka
oyuncuya devredebilirim. Bu hepimize ekstra bir yük teşkil ettiğinden,
karakterini yukarıda anlattığım şekilde ayırmak önceliğimdir.

Karakterin, mevcut olmadığı Encounter’lardan XP almaz.
** Seviye Atlama
Karakterin, maceralarda kazandığı tecrübeleri, yerleşim
yerlerinde yaptığı çalışmalarla birleştirerek seviye atlar.
*** Çalışma Türleri ve Fasiliteler
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Bunun için karakter yaratımı esnasında, ana ve yan olacak
şekilde iki çalışma türü seçersin.

Genellikle karakterin ilk mesleği ana çalışma türünü, ikinci
mesleği ise yan türünü belirler. Karakterlerin çalışma
türlerinde nihai karar bana aittir.

Çalışma türleri şunlardır:

- *Akademik Çalışma (20 gp):* Araştırma, inceleme, deney,
  eğitim, danışma ve uzmanlığı kapsar. Genellikle bilginler
  ve alimler eşliğinde, kütüphanelerde, laboratuvarlarda
  veya arşivlerde yapılır.
- *Pratik Çalışma (10 gp):* Uzmanlığa dayalı pek çok dalı
  içerir. Yabanda hayatta kalma, zanaatkârlık, hırsızlık
  veya dolandırıcılık gibi bir hünerin gelişimine dayalı
  aktivitelerdir. Genellikle yerleşim yerlerinde veya yakın
  civarlarında, benzer meslek dallarından uzmanlarla bir
  arada çalışarak yapılır.
- *Ritüel Çalışması (20 gp):* Törenler, ayinler, meditasyon,
  tasavvur, gizli ilimler ve diğer ruhani pratikleri
  içerir. Bir şeylerle bağ kurmaya dayanır. Rahipler,
  falcılar, büyücüler, şövalyeler, keşişler bu yöntemleri
  kullanır.
- *Savaş Çalışması (10 gp):* Egzersiz, direnç, karşılıklı
  dövüş, hedef talimi, ve benzeri fiziksel idmanları
  kapsar. Kas, refleks ve kondisyona dayalı meslekler için
  gereklidir. Genellikle askeri talim alanları, dövüş
  kulüpleri, manastırlar, idman salonları vb. yerlerde
  yapılır.
- *Sosyal Çalışma (20 gp):* Mesleğine uygun çevrelerle
  temasta bulunmaya dayalı bir çalışma
  türüdür. Zanaatkârlar, dolandırıcılar, sanatçılar, kanaat
  önderleri vb. profesyoneller, benzer toplulukların
  içerisinde bulunarak meziyetlerini geliştirir.

Çalışma türleri, doğaları gereği farklı dinamikler ortaya
çıkarır. Örneğin, hırsızlık yeteneklerini geliştirmek riskli
olabileceği gibi, kazançlı da olabilir. Ritüellerin ruhani
bağları kuvvetlendirmesi, beklenenden uzun zaman
alabilir. Her fasilitenin, bunun dışında da kendine has
nitelikleri olabilir. Bu gibi durumlar, oyun esnasında
ortaya çıkacaktır.
*** Çalışma Periyotları 
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Çalışma fasiliteleri, ekstrem durumlar dışında çoğu yerleşim
yerinde mevcuttur. Karakterin yeterli XP’ye ulaştığında,
seviye atlamak için buralarda çalışma yapması gerekir. Bu
çalışma zamanı, 4 saatlik periyotlardan oluşur.

Karakterin ana çalışma türünde eğitim yapıyorsa, harcaman
gereken periyot sayısı, ulaştığın seviyenin iki katıdır.

Yan türünde çalışma yapıyorsan, harcaman gereken periyot
sayısı, ulaştığın seviyenin iki buçuk (yukarı yuvarla)
katıdır.

Örneğin 3. seviyeye atladığında, ana türünde, 4 saatlik 6
periyotta çalışma yaparsın. Yan türünde ise 8 periyotta
çalışma yaparsın.

Yan türde çalışma daha uzun olsa da, bazı koşullarda daha
elverişli olabilir. Fasiliteye erişememe, farklı faydalar
gözetme, gibi.

Eğitim süresi boyunca ortaya çıkan masrafları ödemen
gerekir. Bunlar, türlerin yanında belirtilmiştir. Bu sürenin
sonunda seviye atlamayı tamamlarsın.
*** Rehberlik
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Seviye atlarken tek başına çalışabileceğin gibi, bir rehbere
de danışabilirsin. Rehberler, alanlarında uzman NPC’lerdir.

Kendi başına çalışırken mevcut sınıfında seviye atlayabilir,
mevcut skill'lerine yeni kademe ekleyebilir, mesleğinin
getirdiği gelişim özelliklerini alabilirsin. Ayrıca mevcut
özelliklerinin devamı olan, veya ön koşullarını tamamladığın
feat'leri edinebilirsin.

Yeni bir meslekte ilk seviyeni almak, yeni bir skill'e giriş
yapmak, karakter özelliklerinin devamı niteliğinde olmayan
bir feat'i almak için rehberlik gerekir.

Karakter gelişiminde rehberlik gerekip gerekmediğini
belirlerken son karar bana aittir.

Rehberlik yapacak NPC’lere ulaşman her zaman kolay
olmayabilir. Çoğu zaman eğitim karşılığında karakterinin bu
kişilere bir şeyler sunması gerekir. Dolayısıyla oyun
sırasında bu gibi karakterleri teşhis edip, onlardan
istifade etme yollarını gözetmek, lehine olur.

Rehberler, karakterine ana kitapta olmayan feat'ler,
meslekler, büyüler veya özellikler sunabilir. İlaveten seni
seviye atlarken attığın düşük HP zarlarına karşı korur. Son
olarak da, rehber eşliğinde çalışarak seviye atlarsan, o
seviye boyunca %10 XP bonusu kazanırsın.

------
* Dinler ve Tanrılar
Arz’ın en yaygın iki inancı, Yeni Tanrı Dini ve Eski
Tanrılar'dır.
** Yeni Tanrı Dini
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Emperyal dönemde İmparatorluk’ta ortaya çıkan Yeni Tanrı
Dini, bugün Arz’ın en yaygın inancıdır. Rahipleri, diyarın
dört bir yanındaki katedraller ve bazilikalarda dini hizmet
sunar.

Bu inanç, Azizlerin Dini olarak da bilinir. Okuyucularına
ahlaki ve felsefi öğretiler aktaran Azizlerin Kutsal Kitabı
ile önce İmparatorluk’a, sonra da dünyaya yayılmıştır. Bu
ciltler, insan formundaki ilahı varlıklar olan Azizler’in
hikayelerini anlatır. Azizlerin Kutsal Kitabı beş bölümden
oluşur. Bunlar:

- *Kral ve Şövalyelerin Kitabı.* İyi Kral ve Şövalyeleri’nin
  adalet ve doğruluk için çıktıkları yolculuğu anlatır.
- *Gözcülerin Kitabı.* Batı Krallıkları’nı gezen üç kadının
  öyküsünü aktarır: Bakire, Ana ve Kocakarı. Bu ciltte,
  kader, gelecek, ve aile temaları yaygındır.
- *İkizlerin Kitabı.* Bilgin ve Demirci’nin temel olarak
  gelişim, sabır ve arayışa yönelik öğretiler içeren
  hikayesini anlatır.
- *Gezginin Kitabı.* Kahraman bir Gezgin’in İmparatorluk ve
  İç Deniz kıyısındaki sürükleyici maceralarını
  anlatır. Çoğu bölgede en popüler cilt budur.
- *İsimsiz Kitap.* Yabancı tarafından yazılan bu garip
  kitap, bazen diğer ciltlerden bağımsız kısa öyküler
  anlatır, bazense diğer Azizler’in hikayelerine
  farklı—hatta kimi zaman sorgulayıcı—yaklaşımlar sunar.

Kitaplarda, Azizler bir Yaratıcı’ya işaret etmekte;
insanlara onun yolundan gitmek, hayatı ve medeniyeti doğru
biçimde idare etmek için öğretiler sunmaktadır.

Tabii satır aralarında karanlık bazı figürlerden de
bahsedilir. İyi Kral, takipçilerini Azapgetiren’e karşı
uyarır. İkizler ve Gezginin Kitapları, Aldatan’ın ölümlüler
arasında gizlice dolaştığını anlatır. Gözcülerin Kitabı’nda
ise Olmayan adlı rahatsız edici bir varlığa değinilmektedir.
** Eski Tanrılar
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Eski Tanrılar’ın hangilerinin tanrı, hangilerinin doğa ruhu
olduğu tartışmalıdır. Paganların kendileri bile çağlar
boyunca bu güçler üzerinde bir uzlaşmaya varamamıştır. Eski
Din, ahlaki öğretilerden ziyade, doğal güçlerle uyum içinde
yaşamaya, onların tehlikelerinden sakınmaya yöneliktir.
*** Avandra
Şans, değişim, macera ve seyahati temsil eder. Medeni
dünyada olmasa da, ıssız yol kenarlarında pek çok sunağı
vardır. Gezginler, tüccarlar, her türden maceracılar onun
yolundan gider.
*** Bahamut
Platin ejderha Bahamut, adalet, himaye ve onur
tanrısıdır. Eski Tanrı paladinleri, metalik ejderhalar ve
dragonborn'lar onun asil yolunu takip eder.
*** Ioun
Bilgelik, yetenek ve kehanetler tanrıçasıdır. Alimler,
kahinler, büyücüler onun yolunu izler. Kütüphaneler ve
akademiler, çoğu zaman onun ismine adanır.
*** Kord
Fırtına ve savaş tanrısıdır. Güç, kuvvet ve yiğitliği temsil
eder. Yıldırımların efendisi, vahşi ve dizginsiz bir
ilahtır. Savaşçılar, denizciler, atletler ondan medet umar.
*** Kuzgun Kraliçe
Ölüm tanrısının adı uzun zaman önce unutulmuştur, bugün o
yalnızca Kuzgun Kraliçe adıyla bilinir. Kadere
hükmeder. Aynı zamanda kışı ve ölümlü yaşamın sonunu
sembolize eder. Pek çok yerde, dünyadan göçen ruhlara eşlik
etmesi için ona adaklar adanır.
*** Melora
Yaban diyarlar ve denizlerin tanrıçasıdır. Hem vahşi hayatı,
hem barışçıl doğayı temsil eder. Kolcular, avcılar,
denizciler ona tapar.
*** Pelor
Güneş ve yaz tanrısıdır. Ayrıca zamanın
efendisidir. Karanlığa, acıya ve kötülüğe karşı durmak
isteyenler ona sığınır. Tarım ve bereketi temsil ettiğinden,
insan dünyasındaki en yaygın ilahlardandır.
*** Sehanine
Ay ve sonbahar tanrıçası Sehanine, aldatmaca, gölgeler ve
ilüzyonların ilahıdır. Aşkı, rüyaları ve hayalleri temsil
eder. Gözcüler, hırsızlar ve aşıklar ondan lütuf dilerler.

------
* Oyun Konsepti
/Kayıp Kıta Serüvenleri/ 26 Nisan'da başlayacak, /Dungeons &
Dragons v.3.5/ kural sistemiyle oynanacak bir FRP
oyunudur. Haftalık seanslar şeklinde, altı—on ay arası
sürecektir. Oyunun genel konsepti aşağıdadır.
** Kayıp Senua Kıtası
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Kılıç ve büyünün hüküm sürdüğü kadim Arz dünyasının
güneybatısında Kayıp Senua Kıtası uzanır. Burası balta
girmemiş ormanlar, fırtınalı sahiller ve öfkeli volkanlarla
doludur. Kabileler, ilkel canavarlar ve köklü elemental
güçlere ev sahipliği yapar.

Karanlık Çağ'ın sonunda, bölge kabilelerinin lideri Kraliçe
II. Matari, kolonicilere kıtanın kapılarını açma kararı
verir. Yeni Lejyon'la bir anlaşma imzalar. Buna göre
lejyonerler, kazançlarını Kraliçe'yle paylaşmak şartıyla,
kıtada faaliyet gösterebilecektir. Yeni Lejyon, Arz'ın dört
bir yanından maceracıları, tüccarları, bilginleri ve
zanaatkârları Senua'ya davet eder.

Grup, bu çağrıya kulak verip, sıradan hayatlarını geride
bırakan yabancılar olarak yola başlar. Hepsi kendi
gayelerinin peşindedir. Ancak zamanla birbirlerine
güvenmeyi, ve beraber çalışmayı öğrenirler.
** Mücadele ve Fırsatlar
:PROPERTIES:
:UNNUMBERED: notoc
:END:
İlk görevlerinde, müstakbel maceracıları şans bir araya
getirir. Sonrasında bölgedeki yerleşim yerlerinde başka
macera fırsatları keşfederler. Bunlardan birini kovalamaya
karar verdiklerinde, genellikle bir ön hazırlık yaparak,
gerekli erzaklar ve önemli bilgiler edinirler. Ardından
yerleşim yerinden ayrılıp, yaban doğanın çetin şartlarında
yolculuk ederek macera lokasyonuna ulaşırlar.

Buradaki engelleri ve zorlukları aşarak maceranın ana
hedefini gerçekleştirmeye çalışırlar. Bu, vahşi bir canavarı
avlama, doğal bir bölgeyi keşfetme veya unutulmuş bir
harabeyi araştırma gibi şeyler olabilir.

Hedeflerinde başarılı olsalar da, olmasalar da, yerleşim
yerine dönerler. Burada macerada elde ettikleri kazanımları
değerlendirir, çalışarak seviye atlarlar. Bir yandan da
dinlenip güç toplarlar. Yerleşim yerleri bunlar dışında da
sosyalleşme, bağlantılar kurma, bilgi edinme vb. cazip
imkanlar da sunar. Eninde sonunda yeni bir macera kendini
gösterir, ve döngü tekrar başlar.

Grup kısa sürede koloni bölgesinin mucizeler, tehlikeler ve
sırlarla dolu olduğunu görür. Maceraları esnasında bunları
yavaş yavaş keşfeder, ve bunlarla nasıl başa çıkacağına
karar verir. Eylemleri onları, Yeni Lejyon, kabileler, veya
bölgedeki diğer aktörlerle ortak ya da rakip haline
getirebilir. Nihayetinde bölgenin kaderini belirleyecek
seçimlerin bir parçası olabilirler. Tabii uyanmakta olan
ilkel bir gücün hiddeti altında ezilip gitmezlerse.
** Serüvenin İlk Adımı
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Hikaye başlarken grup Karuga Limanı'nda toplanır. Lejyon
onları Kadim Ruhlar Ormanı kıyısındaki bir oduncu kampını
araştırmak için görevlendirir. Hedef bir süredir
kendilerinden haber alınamayan işçilerin kaderini ortaya
çıkarmaktır. Bölgenin amansız tehlikeleriyle yüzleşmek üzere
vahşi doğaya ilk adımlarını atarlar. Çok geçmeden
karşılarında meşum bir kehanet bulacaklardır:

/Kaynayan denizler ve fokurdayan volkanların içinden/
/Uyanacak ilkel bir güç en korkunç derinlerden./
/Elementler bir kaos ve yıkım seliyle köpürecek/
/Denge ancak gök ve yer birleşince gelecek./

------
* Karakter Yaratımı
/Kayıp Kıta Serüvenleri/ için 19 Nisan Çarşamba saat 18'de
karakter yaratımı yapacağız.

Öncesinde, aşağıdaki seçenekleri değerlendirip iki farklı
karakter konsepti seçmelisin. Bunun için kulağına
eğlenceli gelen, oynamak istediğin bir *ırk*, *meslek* ve
*motivasyon* kombinasyonu belirle.

Örneğin, "İyilik yapmaya çalışan İnsan bir Savaşçı." Veya
"Dwarf, Cleric, Motivasyon: İnancını Yaymak," gibi. Bunu iki
farklı karakter için tekrarla. Ve iki tercihini Çarşamba
gününden önce bana özelden ulaştır.

Herkes tercihlerini gönderdiğinde bunları okuyup
değerlendireceğim. Ve karakterleri birlikte yaratacağız.

(*Önemli Not.* Tercihlerini bu şekilde önden göndermeyen
oyuncular, karakter yaratımında attıkları skor zarlarını
kabiliyetlerine diledikleri gibi yerleştirme hakkından
mahrum kalacaktır.)
** Irklar
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Oyunda seçebileceğin ırklar aşağıdadır:
*** İnsan
İnsanlar, Arz'ın en baskın ırkıdır. Çeşitlilikleri,
adaptasyonları ve hırslarıyla bilinirler. Oyundaki insan
karakterler kolonici veya yerli olabilir.

Örnek isimler:

- Batı Krallıkları:
  * Ander, Desmon, Korven, Stedd, Wilas
  * Doris, Elmira, Hedra, Margot, Trisa
- İmparatorluk:
  * Bato, Cassius, Flavius, Hektor, Marius
  * Cintia, Justina, Iris, Optima, Regina
- Buzyeli: 
  * Gunthar, Ragmar, Sigmund, Torvald, Ulf
  * Freya, Gunhild, Hilda, Ingrid, Svena
- Özgür Şehirler:
  * Anton, Lorenza, Markon, Renzo, Salazar
  * Bella, Cecila, Dona, Luisa, Marena
- Senua: 
  * Atohi, Hemak, Nahotl, Senua, Tenoch
  * Aki, Kenoi, Neke, Samose, Waneha
*** Cüce
Cüceler, dağlardaki görkemli maden-kentlerinde yaşayan,
tıknaz ve babayiğit bir halktır. Sıkı çalışmaları,
materyalist yapıları ve dirençleriyle bilinirler.
Huysuzlukları ve inatları meşhurdur. Zor dost edinirler,
düşmanlarını ise asla unutmazlar.

Örnek isimler:

- Angmar, Barkus, Magnar, Rurik, Tordek, Ungrim
- Agna, Bianka, Katlin, Mael, Orla, Thurisa
*** Elf
Mağrur ve zarif elfler, kadim ve uzun ömürlü bir
halktır. Dışa kapalı bir yaşam sürerler. Dövüş, müzik,
sanat, sihir gibi meziyet isteyen şeylere büyük saygı
duyarlar. Gezgin ruhlu elf maceracılar, bazen gizli
ormanlarından ayrılıp insan diyarlarına göç eder.

Örnek isimler:

- Benweth, Elros, Gerthas, Quarion, Sindel
- Amarys, Caelynn, Elrosine, Mirena, Quelenna
*** Buçukluk
Buçukluklar, küçük, dostane, ve becerikli bir
halktır. İnsanlarla iç içe yaşarlar. Sinsilik ve
meraktaki namları, çok da temelsiz değildir. Yuva
sıcaklığına düşkün olsalar da, çoğu maceraperest bir ruh
taşır, ve hayatının bir noktasında yollara düşer.

Örnek isimler:

- Arn, Finn, Milo, Peryn, Reed, Rhent
- Bree, Dori, Fara, Merla, Oona, Tess
*** Genasi
Damarlarında elemental varlıkların kanını taşıyan genasiler,
Senua'da yaygındır. Hava, su, toprak ve ateş olmak üzere
dört türleri vardır.

Fiziken insanlara benzeseler de çarpıcı farklar
taşırlar. Bunlar element niteliklerine göre değişir: Alev
alev yanan gözler, su altındaymışçasına dalganan saçlar,
daima hafif bir esinti taşıma, veya kayaları andıran bir
cilt gibi.

Karakterleri de taşıdıkları elemente göre şekillenir: Ateş
genasileri genelde enerjik ve öfkelidir, su genasileri
duygusal ve empatik olur, hava genasileri uçarı ve
savruktur, toprak genasileri oturaklı ve ağır kanlıdır,
gibi.

Genasiler genelde Senua adları kullanır. Kimileri takma
isimler tercih edebilir. Örneğin:

- Alaz, Duman, Köz, Mısra, Opal, Poyraz, Zefir

(Genasi statları /Forgotten Realms Campaign Setting/
s.19'dadır.)
#+LATEX: \clearpage
** Meslekler
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Oyunda seçebileceğin meslekler aşağıdadır:
*** Barbarian
Arz'ın vahşi toprakları, pek çok barbar kabilesine ev
sahipliği yapar. Bunların gözü kara dövüşçüleri, bazen
halkını geride bırakıp maceraya atılır. Barbarlar
hiddetlerini bir silah gibi kullanır. 
*** Bard
Bazı ozanlar, yolculukları esnasında kadim fey büyülerinin
sırlarını keşfeder. Bu karizmatik maceracılar; güzel söz,
hikaye ve şarkının gücüyle, yılanı deliğinden çıkarır.
*** Cleric
İmparatorluk’un Yeni Tanrı inancı, Arz’ın en yaygın
dinlerindendir. Rahipler, bu yolda iman ve cesaretle
savaşan, ilahi büyü gücüyle donanmış maceracılardır. Çoğu
inancının doğrularını yaymak için yola düşer.
*** Druid
Druidler Eski Tanrılar’ın yolundan giderek onların
büyülerini öğrenen pagan rahipleridir. Öğretileri ahlaki
tutumlar içermez; onun yerine tabiat güçlerinin düzeniyle
uyumlu şekilde yaşamayı hedefler.
*** Fighter
Savaşçılar, dövüş ve muharebe tekniklerinde uzmanlaşmış
maceracılardır. Güç ve dirençleriyle bilinirler. Kayıp Kıta,
canavarlarla ön saflarda cenk etmeye talip gözüpek
savaşçılara cazip fırsatlar sunar.
*** Paladin
Yeni Tanrı Dini'nin bazı şövalyeleri, Azizler'in
mucizeleriyle kutsanır. Bu mukaddes savaşçılar, diyarı gezip
kötülükle savaşmaya ant içerler. Soyluluk, dürüstlük ve
cesaretleriyle çevresindekilere ilham verirler.
*** Ranger
Kolcular, yaban diyarlarda kötülük ve kaosa geçit vermeyen,
çetin kaşiflerdir. En zorlu doğa koşullarında bile hayatta
kalabilirler. Eski Tanrılar’ın izinden giderek, zamanla
onların büyülerini öğrenirler.
*** Rogue
Hırsızlar ve serseriler; hüner, gizlilik ve aldatmacayla
yolunu bulur. Kurnazlıkları ve türlü maharetlerleriyle her
zorluğa karşı bir çare bulabilirler. Senua, onlar için eşsiz
bir hazine avı şansıdır.
*** Sorcerer
Kimi maceracıların büyü yapmak için büyü kitaplarına veya
hocalara ihtiyacı yoktur. Efsuncular büyünün gücünü
kanlarında taşır. Gizli sanatlara içten gelen bir yetenekle
hükmederek engelleri aşarlar.
*** Wizard
Büyücüler, uzun yıllar süren çalışmalar sonucu büyünün gizli
ilmine vakıf olmuş maceracılardır. Kayıp Kıta, elemental
güçleri ve unutulmuş sırlarıyla, bu kurnaz alimleri kendine
çeker.
** Motivasyonlar
:PROPERTIES:
:UNNUMBERED: notoc
:END:
Motivasyon, karakterinin neden maceralara atıldığını
gösterir. Bazı örnek motivasyonlar aşağıdadır:

1. İyilik Yapmak
2. Başkalarına Yardım Etmek
3. Becerini Kanıtlamak
4. Şan-şöhret Kazanmak
5. Zengin Olmak
6. Yeteneklerinde Ustalaşmak
7. Zaferler Kazanmak
8. Adaleti Sağlamak
9. Vazifeni Yapmak
10. Hakikati Keşfetmek
11. Güç Kazanmak
12. Bilgi Biriktirmek
13. Kaderini Gerçekleştirmek
14. Can Sıkıntını Gidermek
15. Statü Kazanmak
16. İnancını Yaymak
17. Kaos Yaratmak
18. Öfkeni Yatıştırmak
19. Seyahat Tutkunu Tatmin Etmek
20. İntikam Alma
